version: "3.9"

services:
  db:
    image: mysql:${VERSION}
    container_name: my-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin
    container_name: my-mysqlphpmyadmin
    restart: unless-stopped
    ports:
      - "8078:80"
    environment:
      PMA_HOST: db

volumes:
  mysql_data:
